name:                tex-haskell
version:             0.1.0.0
github:              "jnbooth/tex-haskell"
license:             BSD3
author:              "Joshua Booth"
maintainer:          "joshua.n.booth@gmail.com"
copyright:           "2019 Joshua Booth"

extra-source-files:
- README.md

default-extensions:
# Package-specific
- NoImplicitPrelude
# Removing artificial limitations
- ConstraintKinds
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
# Syntactic sugar
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- TupleSections
- UnicodeSyntax
- ViewPatterns
# More powerful deriving
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- ScopedTypeVariables
# Unlikely to be used, but no drawbacks
- BangPatterns
- DefaultSignatures
- KindSignatures
- PatternSynonyms
- RankNTypes
- TypeApplications
- TypeOperators
# Unfortunate necessities
- OverloadedStrings

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tex-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- case-insensitive
- classy-prelude
- conduit
- containers
- dotenv
- forkable-monad
- html-conduit
- http-conduit
- mtl
- multimap
- network
- postgresql-simple
- random
- text
- text-icu
- time
- transformers
- xml-conduit
- unordered-containers

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wredundant-constraints
    - -fwarn-tabs
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-uni-patterns
    - -fno-warn-orphans
    - -fno-warn-type-defaults
    # - +RTS -xc

executables:
  tex-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tex-haskell

tests:
  tex-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tex-haskell
